points:
  pt0:
  - 0.19
  - 0.0
  - -0.015
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0
  pt1:
  - 0.19
  - 0.0
  - -0.01
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0
  pt2:
  - 0.19
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  - 0
