<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="slidebot">

<!-- slidebot is a robot that has 1 linear and 1 rotational degree of freedom -->
<xacro:property name="yaml_file" value="$(find homework2)/config/arm.yaml" />
<xacro:property name="props" value="${load_yaml(yaml_file)}"/>
<xacro:property name="L1" value="${props['L1']}" />
<xacro:property name="L2" value="${props['L2']}" />
<xacro:property name="radius" value="0.5" />

<!-- The base from which the body slides -->




<!-- create visual fro joints  -->
<xacro:macro name="ball" params="link_name posX posZ prefixFrom">
<link name="${link_name}" >
  <visual>
    <geometry>
      <sphere radius="${radius/2}" />
     </geometry>
     <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
     <material name="green_mat">
         <color rgba="0 1 0 1" />
     </material>
   </visual>
</link>

  <joint name="ball_link_${link_name}" type="fixed">
      <parent link="${prefixFrom}"/>
      <child link="${link_name}"/>
      <origin xyz="${posX} 0 ${posZ}"/>
  </joint>    
</xacro:macro>




<!-- create links and joints  -->
<xacro:macro name="myLink" params="prefix prefixFrom length ahead posZ colo">
    <link name="${prefix}">
        <visual>
            <geometry>
                <cylinder radius="0.2" length="${length}" />
            </geometry>
            <origin xyz="${length/2} 0.0 0.0" rpy="0 ${pi/2}  0" />
            <material name="blue_mat${prefix}">
              <color rgba="0 ${colo*1} 1 1" />
            </material>
        </visual>

    </link>

    <joint name="joint_${prefix}" type="continuous">
        <parent link="${prefixFrom}"/>
        <child link="${prefix}"/>
        <origin xyz="${ahead} 0 ${posZ}"/>
        <axis xyz="0 0 1"/>
    </joint>
</xacro:macro>



<!-- visual for my base frame -->
  <link name="base">
    <visual>
      <geometry>
        <box size="0.5 0.5 0.5"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0.25"/>
      <color rgba="0 1 0 1" />
    </visual>
  </link>

<!-- create axis and visual from end effector -->
    <link name="end_effector">
    <visual>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0.05 0 0"/>
      <color rgba="0 1 0 1" />
    </visual>
  </link>

  <joint name="Link_2_to_endEFF" type="fixed">
    <parent link="Link_2"/>
    <child link="end_effector"/>
    <origin xyz="${L2} 0 0.0"/>
  </joint>



<xacro:myLink prefix="Link_1" prefixFrom="base"   length="${L1}" ahead="0.0" posZ="1.0"   colo="0.0"/>
<xacro:myLink prefix="Link_2" prefixFrom="Link_1" length="${L2}" ahead="${L1}" posZ="0.0" colo="1.0"/>
<xacro:ball link_name="ball1" posX="0.0" posZ="0.0" prefixFrom="Link_1" />
<xacro:ball link_name="ball2" posX="${L1}" posZ="0.0" prefixFrom="ball1"/>
</robot>